import type { Course } from "./types";

export const mockCourses: Course[] = [
  {
    id: "cs135",
    code: "CS 135",
    title: "Designing Functional Programs",
    description: "An introduction to programming principles for students with little or no programming experience. This course is not for students in the computer science program.",
    credits: 0.5,
    prerequisites: [],
    faculty: "Computer Science",
    level: 100,
    availability: ["Fall", "Winter", "Spring"],
  },
  {
    id: "math135",
    code: "MATH 135",
    title: "Algebra for Honours Mathematics",
    description: "An introduction to the rigorous language of mathematics. Properties of the integers, modular arithmetic, the Fundamental Theorem of Arithmetic. Complex numbers. Polynomials.",
    credits: 0.5,
    prerequisites: [],
    faculty: "Math",
    level: 100,
    availability: ["Fall", "Winter", "Spring"],
  },
  {
    id: "cs246",
    code: "CS 246",
    title: "Object-Oriented Software Development",
    description: "Introduction to object-oriented programming and to tools and techniques for software development. C++, memory management, debugging, and testing.",
    credits: 0.5,
    prerequisites: ["CS 135"],
    faculty: "Computer Science",
    level: 200,
    availability: ["Fall", "Winter"],
  },
  {
    id: "eng101",
    code: "ENGL 109",
    title: "Introduction to Academic Writing",
    description: "This course provides instruction and practice in university-level reading, writing, and reasoning.",
    credits: 0.5,
    prerequisites: [],
    faculty: "Arts",
    level: 100,
    availability: ["Fall", "Winter", "Spring"],
  },
  {
    id: "chem120",
    code: "CHEM 120",
    title: "Physical and Chemical Properties of Matter",
    description: "Introduction to chemistry, with an emphasis on the properties of chemical substances and the reactions that they undergo.",
    credits: 0.5,
    prerequisites: [],
    faculty: "Science",
    level: 100,
    availability: ["Fall", "Winter"],
  },
  {
    id: "gen_e_123",
    code: "GENE 123",
    title: "Electrical Circuits and Instrumentation",
    description: "Circuit analysis, Ohm's and Kirchhoff's laws, voltage and current dividers, Thevenin and Norton equivalent circuits, and operational amplifiers.",
    credits: 0.5,
    prerequisites: [],
    faculty: "Engineering",
    level: 100,
    availability: ["Winter"],
  },
    {
    id: "cs350",
    code: "CS 350",
    title: "Operating Systems",
    description: "An introduction to the fundamentals of operating systems. Concurrency, synchronization, processes and threads, memory management, and file systems.",
    credits: 0.5,
    prerequisites: ["CS 246"],
    faculty: "Computer Science",
    level: 300,
    availability: ["Fall", "Spring"],
  },
  {
    id: "math239",
    code: "MATH 239",
    title: "Introduction to Combinatorics",
    description: "An introduction to enumerative combinatorics and graph theory.",
    credits: 0.5,
    prerequisites: ["MATH 135"],
    faculty: "Math",
    level: 200,
    availability: ["Fall", "Winter", "Spring"],
  },
    {
    id: "econ101",
    code: "ECON 101",
    title: "Introduction to Microeconomics",
    description: "An introduction to the principles of microeconomics. Supply and demand, consumer theory, production and cost, market structure, and government intervention.",
    credits: 0.5,
    prerequisites: [],
    faculty: "Arts",
    level: 100,
    availability: ["Fall", "Winter", "Spring"],
  },
  {
    id: "cs486",
    code: "CS 486",
    title: "Introduction to Artificial Intelligence",
    description: "Fundamental concepts and techniques of artificial intelligence. Problem solving, knowledge representation, reasoning, planning, and learning.",
    credits: 0.5,
    prerequisites: ["CS 350"],
    faculty: "Computer Science",
    level: 400,
    availability: ["Fall"],
  },
];
