import { RoadmapGenerator } from "@/components/roadmap-generator";

export default function RoadmapPage() {
  return (
    <div className="container mx-auto px-4 py-8 md:px-6">
      <div className="space-y-4 mb-8 text-center">
        <h1 className="text-3xl font-bold tracking-tight font-headline sm:text-4xl">
          AI-Powered Roadmap Generator
        </h1>
        <p className="text-muted-foreground max-w-2xl mx-auto">
          Kickstart your degree planning with a personalized course roadmap generated by AI. Just provide a few details about your academic goals, and let GradX handle the rest.
        </p>
      </div>
      
      <div className="max-w-4xl mx-auto">
        <RoadmapGenerator />
      </div>
    </div>
  );
}
